export const RECIPE_SEARCH_REQUEST = "RECIPE_SEARCH_REQUEST"
export const RECIPE_SEARCH_FAILURE = "RECIPE_SEARCH_FAILURE"

export const RECIPE_SEARCH_SUCCESS = "RECIPE_SEARCH_SUCCESS"
export const RECIPE_DETAILS_VIEW_CLICK = "RECIPE_DETAILS_VIEW_CLICK"
export const RECIPE_DETAILS_SUCCESS = "RECIPE_DETAILS_SUCCESS"
